database:
  driver: mysql # 数据库驱动
  host: localhost # 域名
  port: 3307 # 端口号
  database: demo # 数据库名称
  username: root # 用户名
  password: 123456 # 密码
  charset: utf8mb4 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量