// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChessColumns holds the columns for the "chess" table.
	ChessColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "before", Type: field.TypeString},
		{Name: "after", Type: field.TypeString},
		{Name: "count", Type: field.TypeInt64},
	}
	// ChessTable holds the schema information for the "chess" table.
	ChessTable = &schema.Table{
		Name:       "chess",
		Columns:    ChessColumns,
		PrimaryKey: []*schema.Column{ChessColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChessTable,
	}
)

func init() {
	ChessTable.Annotation = &entsql.Annotation{
		Table: "chess",
	}
}
