// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chesss/pkg/ent/chess"
	"chesss/pkg/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChessUpdate is the builder for updating Chess entities.
type ChessUpdate struct {
	config
	hooks    []Hook
	mutation *ChessMutation
}

// Where appends a list predicates to the ChessUpdate builder.
func (cu *ChessUpdate) Where(ps ...predicate.Chess) *ChessUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetBefore sets the "before" field.
func (cu *ChessUpdate) SetBefore(s string) *ChessUpdate {
	cu.mutation.SetBefore(s)
	return cu
}

// SetAfter sets the "after" field.
func (cu *ChessUpdate) SetAfter(s string) *ChessUpdate {
	cu.mutation.SetAfter(s)
	return cu
}

// SetCount sets the "count" field.
func (cu *ChessUpdate) SetCount(i int64) *ChessUpdate {
	cu.mutation.ResetCount()
	cu.mutation.SetCount(i)
	return cu
}

// AddCount adds i to the "count" field.
func (cu *ChessUpdate) AddCount(i int64) *ChessUpdate {
	cu.mutation.AddCount(i)
	return cu
}

// Mutation returns the ChessMutation object of the builder.
func (cu *ChessUpdate) Mutation() *ChessMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChessUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChessUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChessUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChessUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cu *ChessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(chess.Table, chess.Columns, sqlgraph.NewFieldSpec(chess.FieldID, field.TypeInt64))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Before(); ok {
		_spec.SetField(chess.FieldBefore, field.TypeString, value)
	}
	if value, ok := cu.mutation.After(); ok {
		_spec.SetField(chess.FieldAfter, field.TypeString, value)
	}
	if value, ok := cu.mutation.Count(); ok {
		_spec.SetField(chess.FieldCount, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedCount(); ok {
		_spec.AddField(chess.FieldCount, field.TypeInt64, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChessUpdateOne is the builder for updating a single Chess entity.
type ChessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChessMutation
}

// SetBefore sets the "before" field.
func (cuo *ChessUpdateOne) SetBefore(s string) *ChessUpdateOne {
	cuo.mutation.SetBefore(s)
	return cuo
}

// SetAfter sets the "after" field.
func (cuo *ChessUpdateOne) SetAfter(s string) *ChessUpdateOne {
	cuo.mutation.SetAfter(s)
	return cuo
}

// SetCount sets the "count" field.
func (cuo *ChessUpdateOne) SetCount(i int64) *ChessUpdateOne {
	cuo.mutation.ResetCount()
	cuo.mutation.SetCount(i)
	return cuo
}

// AddCount adds i to the "count" field.
func (cuo *ChessUpdateOne) AddCount(i int64) *ChessUpdateOne {
	cuo.mutation.AddCount(i)
	return cuo
}

// Mutation returns the ChessMutation object of the builder.
func (cuo *ChessUpdateOne) Mutation() *ChessMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ChessUpdate builder.
func (cuo *ChessUpdateOne) Where(ps ...predicate.Chess) *ChessUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChessUpdateOne) Select(field string, fields ...string) *ChessUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chess entity.
func (cuo *ChessUpdateOne) Save(ctx context.Context) (*Chess, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChessUpdateOne) SaveX(ctx context.Context) *Chess {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChessUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChessUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (cuo *ChessUpdateOne) sqlSave(ctx context.Context) (_node *Chess, err error) {
	_spec := sqlgraph.NewUpdateSpec(chess.Table, chess.Columns, sqlgraph.NewFieldSpec(chess.FieldID, field.TypeInt64))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chess.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chess.FieldID)
		for _, f := range fields {
			if !chess.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chess.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Before(); ok {
		_spec.SetField(chess.FieldBefore, field.TypeString, value)
	}
	if value, ok := cuo.mutation.After(); ok {
		_spec.SetField(chess.FieldAfter, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Count(); ok {
		_spec.SetField(chess.FieldCount, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedCount(); ok {
		_spec.AddField(chess.FieldCount, field.TypeInt64, value)
	}
	_node = &Chess{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
