// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chesss/pkg/ent/chess"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChessCreate is the builder for creating a Chess entity.
type ChessCreate struct {
	config
	mutation *ChessMutation
	hooks    []Hook
}

// SetBefore sets the "before" field.
func (cc *ChessCreate) SetBefore(s string) *ChessCreate {
	cc.mutation.SetBefore(s)
	return cc
}

// SetAfter sets the "after" field.
func (cc *ChessCreate) SetAfter(s string) *ChessCreate {
	cc.mutation.SetAfter(s)
	return cc
}

// SetCount sets the "count" field.
func (cc *ChessCreate) SetCount(i int64) *ChessCreate {
	cc.mutation.SetCount(i)
	return cc
}

// SetID sets the "id" field.
func (cc *ChessCreate) SetID(i int64) *ChessCreate {
	cc.mutation.SetID(i)
	return cc
}

// Mutation returns the ChessMutation object of the builder.
func (cc *ChessCreate) Mutation() *ChessMutation {
	return cc.mutation
}

// Save creates the Chess in the database.
func (cc *ChessCreate) Save(ctx context.Context) (*Chess, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ChessCreate) SaveX(ctx context.Context) *Chess {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ChessCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ChessCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ChessCreate) check() error {
	if _, ok := cc.mutation.Before(); !ok {
		return &ValidationError{Name: "before", err: errors.New(`ent: missing required field "Chess.before"`)}
	}
	if _, ok := cc.mutation.After(); !ok {
		return &ValidationError{Name: "after", err: errors.New(`ent: missing required field "Chess.after"`)}
	}
	if _, ok := cc.mutation.Count(); !ok {
		return &ValidationError{Name: "count", err: errors.New(`ent: missing required field "Chess.count"`)}
	}
	return nil
}

func (cc *ChessCreate) sqlSave(ctx context.Context) (*Chess, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ChessCreate) createSpec() (*Chess, *sqlgraph.CreateSpec) {
	var (
		_node = &Chess{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(chess.Table, sqlgraph.NewFieldSpec(chess.FieldID, field.TypeInt64))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Before(); ok {
		_spec.SetField(chess.FieldBefore, field.TypeString, value)
		_node.Before = value
	}
	if value, ok := cc.mutation.After(); ok {
		_spec.SetField(chess.FieldAfter, field.TypeString, value)
		_node.After = value
	}
	if value, ok := cc.mutation.Count(); ok {
		_spec.SetField(chess.FieldCount, field.TypeInt64, value)
		_node.Count = value
	}
	return _node, _spec
}

// ChessCreateBulk is the builder for creating many Chess entities in bulk.
type ChessCreateBulk struct {
	config
	builders []*ChessCreate
}

// Save creates the Chess entities in the database.
func (ccb *ChessCreateBulk) Save(ctx context.Context) ([]*Chess, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Chess, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ChessCreateBulk) SaveX(ctx context.Context) []*Chess {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ChessCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ChessCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
